version: "3.8"

services:

  frontend:
    build:
      context: ./frontend
    container_name: frontend

  backend:
    image: clue/json-server
    container_name: backend
    volumes:
      - ./frontend/server/db.json:/data/db.json
    command: json-server --host 0.0.0.0 --watch /data/db.json --port 3001
    ports:
      - "3001:3001"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home: